config/routes.rb
Rails.application.routes.draw do

  root 'pages#one'
  
  get 'pages/two'

  get 'pages/three', to: 'pages#three'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-inverse bg-dark">
  <a class=" nav-link disabled" href="#">FirstApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
     
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">One<span class="sr-only">One</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pages_two_path %>">Two</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pages_three_path %>">Three</a>
      </li>
      
    </ul>
  </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Pages#one</h1>
<p>Find me in app/views/pages/one.html.erb</p>




<div class="jumbotron">
  <h1 class="display-3">Oh que genial es el MVC!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

<h1 class="display-2"> Rafael Martinez </h1>

app/views/pages/three.html.erb
<h2>Pages#three</h2>


<p>In est cillum dolore exercitation est exercitation aliquip ipsum sit enim do reprehenderit. Consectetur dolore Lorem cupidatat dolor dolor voluptate. Sint nostrud fugiat occaecat fugiat magna sunt aute dolor aliquip aliquip. Ut sit sit laborum aute qui.</p>

app/views/pages/two.html.erb
<h1>Pages#two</h1>
<p>Find me in app/views/pages/two.html.erb</p>

<div class="container">
<h1 class="display-2"> take a look at my screenShots! </h1>

<%= image_tag('rutasFApp.png') %>
</div>